biology_data = [{"category": "biology", "title": "生命はいつ、どのようにして生まれたのか？"},
                {"category": "biology", "title": "どのような遺伝子が存在するか、またその機能は何か？"},
                {"category": "biology", "title": "ジャンクDNAは何の機能も持っていないのか？"},
                {"category": "biology", "title": "個体の寿命が設けられている意味は何か？"},
                {"category": "biology", "title": "一部の動物達はどうやって長距離の渡り、回遊を行っているのか？"},
                {"category": "biology", "title": "自然界に存在する電場は生物にどのような影響を与えているのか？"},
                {"category": "biology", "title": "免疫系と脳の関係はどうなっているのか？"},
                {"category": "biology", "title": "進化の（生物の変化）実相はいかなるものであるのか？"},
                {"category": "biology", "title": "原始生物から高等生物への進化のメカニズムはどのように発現するのか？"},
                {"category": "biology", "title": "多くの生物が有性生殖で繁殖するのは何故か？"},
                ]
