FROM python:3.9.4-slim

LABEL  maintainer "nukopy <pytwbf201830@gmail.com>"

WORKDIR /app

# install packages
RUN apt-get update \
    && apt-get install -y \
        default-libmysqlclient-dev \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# install Python packages
RUN pip install -U pip && \
    pip install --no-cache-dir poetry
COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false \
    && poetry install

# add source code
COPY ./ ./

# enable "from app.[module] import [func]"
ENV PYTHONPATH "/"
