name: Deploy to production environment

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
jobs:
  deploy:
    name: Deploy to production environment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to production environment
        run: |
          echo "Hello, World!\nI'm deploying..."
      - name: Notify to Discord
        uses: sarisia/actions-status-discord@v1 # https://github.com/sarisia/actions-status-discord
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions
          status: ${{ job.status }}
          nofail: false # when notification failed, this action failed, then workflow failed
